name: kidsenglish
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flip_card: ^0.4.4
  clay_containers: ^0.2.2
  
  splash_screen_view: ^1.0.3
  audioplayers: ^0.16.1
  firebase_admob: ^0.10.0+2
  shared_preferences: ^0.5.12+2
  
  
  
 

  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Drift
      fonts:
        - asset: assets/fonts/drifttyp.ttf
    - family: blackops
      fonts:
        - asset: assets\fonts\BlackOpsOne-Regular.ttf
    - family: agent
      fonts:
        - asset: assets\fonts\AGENTORANGE.ttf
    - family: chasd
      fonts:
        - asset: assets\fonts\CHASD___.ttf
    - family: coiny
      fonts:
        - asset: assets\fonts\coiny-regular.ttf
    - family: gist
      fonts:
        - asset: assets\fonts\GistUprightExtrabold.ttf
    - family: piedra
      fonts:
        - asset: assets\fonts\Piedra-Regular.ttf
    - family: turk
      fonts:
        - asset: assets\fonts\TTimesb.ttf
           
        

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/
     - assets/audios/
     
     
     - assets/images/fil.png

     - assets/images/alphabet/
     - assets/images/vehicles/
     - assets/images/jobs/




     - assets/images/animals/elephant.png
     - assets/images/animals/dog.png
     - assets/images/animals/monkey.png
     - assets/images/animals/penguin.png
     - assets/images/animals/lion.png   
     - assets/images/animals/tiger.png
     - assets/images/animals/donkey.png
     - assets/images/animals/cat.png
     - assets/images/animals/owl.png
     - assets/images/animals/giraffe.png
     - assets/images/animals/turtle.png
     - assets/images/animals/zebra.png

     - assets/images/fruits/apple.png
     - assets/images/fruits/banana.png
     - assets/images/fruits/grapes.png
     - assets/images/fruits/kiwi.png
     - assets/images/fruits/orange.png
     - assets/images/fruits/pear.png
     - assets/images/fruits/pineapple.png
     - assets/images/fruits/strawberry.png

     - assets/images/clothes/coat.png
     - assets/images/clothes/dress.png
     - assets/images/clothes/pant.png
     - assets/images/clothes/shoes.png
     - assets/images/clothes/skirt.png
     - assets/images/clothes/slipper.png
     - assets/images/clothes/socks.png
     - assets/images/clothes/tshirt.png

     - assets/images/colors/black.png
     - assets/images/colors/blue.png
     - assets/images/colors/brown.png
     - assets/images/colors/green.png
     - assets/images/colors/grey.png
     - assets/images/colors/orange.png
     - assets/images/colors/pink.png
     - assets/images/colors/purple.png
     - assets/images/colors/red.png
     - assets/images/colors/white.png
     - assets/images/colors/yellow.png

     - assets/images/foods/bread.png
     - assets/images/foods/egg.png
     - assets/images/foods/hamburger.png
     - assets/images/foods/hotdog.png
     - assets/images/foods/pizza.png
     - assets/images/foods/sandwich.png

     - assets/images/numbers/0.png
     - assets/images/numbers/1.png
     - assets/images/numbers/2.png
     - assets/images/numbers/3.png
     - assets/images/numbers/4.png
     - assets/images/numbers/5.png
     - assets/images/numbers/6.png
     - assets/images/numbers/7.png
     - assets/images/numbers/8.png
     - assets/images/numbers/9.png
     - assets/images/numbers/10.png
     
     

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
 
        
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
